---
- hosts: ws
  become: true 
  ignore_errors: false 
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
      - name: Download resume 
        get_url:
          url: "{{ LINK_URL }}"
          dest: "{{ DESTINATION }}"
          mode: '0644'
      
      - name: Delete downloaded resume
        file: 
          path: "{{ DESTINATION }}"
          state: absent